### ISSUE TITLE
Faire la maquette Figma

### ISSUE THREAD

**Issue by Oomaxime** [Oomaxime/condorsy#10]
Lien Figma : https://www.figma.com/design/bTEgKcaCRVlbE1bkKmwTK1/Condorsy?node-id=0-1&t=VPGxyplnErOuViec-1

- [x]  Page d'accueil
- [x] Page Register
- [x] Page Login
- [x] Page de profil
- [x] Page de creation de scrutin
- [x] Page de consultation de scrutin
- [x] dashboard admin

**Comment by Jeck0v** [comment]
A vérif mais vu le temps qu'il nous reste ça suffira
