### ISSUE TITLE
Requete UC 3 et 4

### ISSUE THREAD

**Issue by Oomaxime** [Oomaxime/condorsy#20]
#### UC 3 : Modification du profil

> **En tant que** : Visiteur
> **Je souhaite** : Modifier mes informations personnelles
> **En** : en remplissant un formulaire de modification

Une personne peut modiifer ses données personnelles, sauf son pseudonyme qui reste invariable.  Les nouvelles informations sont affichées en retour.

#### UC 4 : Suppression du profil

> **En tant que** : Visiteur
> **Je souhaite** : Me désinscrire
> **En** : en cliquant sur un lien idoine

Les profils ne peuvent pas être complètement supprimés, car l'historique des votes devrait être conservé. A tout le moins, les données personnelles de la personne devraient être effacées, sauf son pseudonyme, qui ne peut être réutilisé. Le profil sera marqué comme « fermé » et ne pourra plus être utilisé pour voter.

**Comment by Jeck0v** [comment]
implémenter
