### ISSUE TITLE
Création des requêtes de gestion utilisateur (uc2, 3 & 4)

### ISSUE THREAD

**Issue by Oomaxime** [Oomaxime/condorsy#3]
Il faut préparer les requête pour répondre à ces différents cas d'utilisations : 
#### UC 2 : S'inscrire sur la plate-forme

> **En tant que** : Visiteur
> **Je souhaite** : M'enregistrer comme utilisateur de la plate-forme
> **En** : remplissant un formulaire d'inscription

Pour ce cas d'utilisations, on fera attention, naturellement, à ce que deux personnes ne puissent utiliser le même pseudonyme.

Une fois la personne inscrite, on veut afficher un résumé de son profil.

#### UC 3 : Modification du profil

> **En tant que** : Visiteur
> **Je souhaite** : Modifier mes informations personnelles
> **En** : en remplissant un formulaire de modification

Une personne peut modifier ses données personnelles, sauf son pseudonyme qui reste invariable.  Les nouvelles informations sont affichées en retour.

#### UC 4 : Suppression du profil

> **En tant que** : Visiteur
> **Je souhaite** : Me désinscrire
> **En** : en cliquant sur un lien idoine

Les profils ne peuvent pas être complètement supprimés, car l'historique des votes devrait être conservé. A tout le moins, les données personnelles de la personne devraient être effacées, sauf son pseudonyme, qui ne peut être réutilisé. Le profil sera marqué comme « fermé » et ne pourra plus être utilisé pour voter.

**Comment by AkaTFL** [comment]
Ajout du fichier api.py avec les fonctions correspondant à la connexion à la base mongoDB du projet, ainsi qu'aux UC 2, 3 et 4
