### ISSUE TITLE
Préparation requête UC 1

### ISSUE THREAD

**Issue by Oomaxime** [Oomaxime/condorsy#4]
Sur la page d'accueil on souhaite afficher :

- La liste des des 10 derniers scrutins créés (avec leur titre la date de leur création)

- La liste des 10 derniers scrutins actifs, c'est-à-dire pour lesquels des personnes ont voté

**Comment by Alexis-Gontier** [comment]
Je commence apres les tests

**Comment by Oomaxime** [comment]
@Alexis-Gontier @Kae134  on en est ou de ça du coup ? l'histoirque est bisare
