### ISSUE TITLE
Algont'rytme Condorsy

### ISSUE THREAD

**Issue by Oomaxime** [Oomaxime/condorsy#8]
**_Création de l'algo de résolution des scrutin en suivant la méthode condorcy_**

### Vote proportionnel

Ce cas est le plus simple.

Le votant ne peut choisir qu'une seule réponse.

Lors de la clôture du scrutin, une fonction n'aura qu'à faire la somme de tous le votes et de choisir celle qui a obtenu le plus de suffrages.

### Vote majoritaire

Dans le cas d'un vote majoritaire, la contraint aoutée est que l'option gagnante doit avoir réuni (50% + 1) des voix.

Le votant ne peut toujours choisir qu'une seule réponse.

Il y a pluseurs manières d'implémenter ce scénario, plus ou moins simples. Faites des propositions.

### Vote Condorcet

L'analyse du vote Condorcet est la plus sophistiquée.

Dans ce cas, l'utilisateur est invité à classer les options, sachant que ce classement ne consitue pas un **ordre total**. Chacun est libre de classer plusieurs options au même niveau.

Cela va, en premier lieu, soulever des questions à propos de la représentation du vote du stockage des données.

#### Normalisation du vote

Le but de cette fonction est de produire une chaîne de caractères
normalisée. Admettons par exemple que le vote comporte 4 choix possibles : A, B, C et D. En fonction de la manière dont l’utilisateur aura rempli le formulaire, plusieurs situations peuvent se produire.

##### Le votant a clairement exprimé des choix différents

Par exemple : B => 1 ; C=> 2 ; A => 3 ; D => 4.

Dans ce cas, nous pouvons produire un tableau : [B, C, A, D]

##### Le votant a exprimé des équivalences de choix

Par exemple : B => 1 ; C => 2 ; A => 2 ; D => 4.

Ce choix et tout à fait licite. Il indique simplement une absence de préférence entre lesoptions C et A.

Dans ce cas, nous pouvons plutôt produire un tableau : [B, [C, A], D]

Remarquons que les nombres 1 .. 4 n’ont pas réellement d’importance. Ce qui compte c’est l’indice de l’option dans le tableau.

##### Le votant s’est abstenu dans certains choix

Par exemple : B => 1 ; C => NULL ; A => 2 ; D => 4.

Dans ce cas, les options non déterminées sont consédérées comme nulles. Vous pouvez alors considérer les deux stratégies suivantes :

1. Les nuls ne sont pas comptabilisés, doù le tableau [B, A, D]

2. Les nuls se voient attribuer l’importance moindre, d’où le tableau [B, A, D, C]

#### Analyse du vote

C’est la partie la plus complexe du système. Elle est décrite sur le simulateur donné en ressource. L’algorithme de Condorcet peut être
décrit de la manière suvante :

1. Pour chaque vote :
   
   1. Prendre un couple d’options ordonné (par exemple [A,B]) et initialiser un score à 0
      1. Si A est mieux classé que B, ajouter 1 au score
      2. Si B est mieux classe que A retrancher 1 au score
      3. Si A et B sont à égalité, rien
      4. Ranger le couple dans un tableau (ou le mettre jour s’il existe déjà)

2. La liste des couples est ensute triée par score décroissant.

3. L’étape suivante consiste à construire un graphe orienté
   
   1. Pour chaque couple :
      
      1. Si le score est positif ou nul, inscrire le premier élément comme clef d’un tableau associatif et ranger le second élément dans le tableau des valeurs avec le score
      2. Si le score est négatif, procéder à l’inverse
      3. Si la clef existait déjà, on met à jour simplement la liste des valeurs
         4. Si un cycle est détecté, le dernier arc est supprimé

4. On cherche maintenant dans ce nouveau tableau les choix qui ne sont pas référencés en tant que valeur (c’est-à-dire les choix qui gagnent sur tous le autres. S'il y en a plusieurs, on les classe suvant la somme des scores décroissante
   
       1. On supprime ces clefs du tableau  
       2. On recommance jusqu’à ce que le tableau soit vide
       
 ## Ressources

### Systèmes électoraux

- [Système électoraux](https://fr.wikipedia.org/wiki/Syst%C3%A8me_%C3%A9lectoral) [Wikipedia]
- [Méthode de Condorcet](https://fr.wikipedia.org/wiki/M%C3%A9thode_de_Condorcet) [Wikipedia]
- [Méthode  de Schulze](https://fr.wikipedia.org/wiki/M%C3%A9thode_de_Schulze) [Wikipedia]
- [Décider ensemble](https://www.deciderensemble.com/observatoire) [Observatoire de la Civic Tech]
- [Référentiel des « Civic Tech » actives en France](https://assets-global.website-files.com/65717d03eaee09aef74995dc/65ba6c3ad603ffd57115f451_VF_Analyse-referentiel-0522.pdf) [PDF]
- [Civic Tech](https://www.cnil.fr/fr/technologies/civic-tech) [CNIL]
- [Civic Tech, données et Demos](https://www.cnil.fr/fr/civic-tech-donnees-et-demos-une-exploration-des-interactions-entre-democratie-et-technologies) [CNIL]
- [Technologie civique](https://fr.wikipedia.org/wiki/Technologie_civique) [Wikipedia]

**Comment by Oomaxime** [comment]
@Kae134 petit point la dessus ?

**Comment by Kae134** [comment]
Je vais finir l'algo ce week end sauf si besoin en urgence
